[versions]
asm = "9.9.1"
junit = "6.0.3"
indra = "4.0.0"

jbAnnos = "26.1.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asmCommons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jbAnnos" }

jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
platformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

gradle-kotlin-dsl = "org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:6.4.2"
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin" }
gradle-plugin-indra = { module = "net.kyori.indra:net.kyori.indra.gradle.plugin", version.ref = "indra" }
gradle-plugin-publish = { module = "net.kyori.indra.publishing:net.kyori.indra.publishing.gradle.plugin", version.ref = "indra" }
gradle-plugin-checkstyle = { module = "net.kyori.indra.checkstyle:net.kyori.indra.checkstyle.gradle.plugin", version.ref = "indra" }
gradle-plugin-javadocLinks = "org.incendo.cloud-build-logic.javadoc-links:org.incendo.cloud-build-logic.javadoc-links.gradle.plugin:0.0.18"


[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indraCheckstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indraPublishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
javadocLinks = { id = "org.incendo.cloud-build-logic.javadoc-links", version = "0.0.18" }
