[versions]
asm = "9.8"
junit = "5.13.3"
junitPlatform = "1.13.3"
indra = "3.1.3"

jbAnnos = "26.0.2"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asmCommons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jbAnnos" }

jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
platformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indraCheckstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
indraPublishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
javadocLinks = { id = "org.incendo.cloud-build-logic.javadoc-links", version = "0.0.16" }
